apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJnc21sZyIsInBhc3N3b3JkIjoiZ3NtbGdAZG9ja2VyIiwiZW1haWwiOiJnc21sZy5jb21AZ21haWwuY29tIiwiYXV0aCI6IlozTnRiR2M2WjNOdGJHZEFaRzlqYTJWeSJ9fX0K
kind: Secret
metadata:
  name: regcred
  namespace: test
type: kubernetes.io/dockerconfigjson
