apiVersion: v1
data:
  password: Qk9UQHdlYjEyMw==
  port: NDY1
  tls: VHJ1ZQ==
  url: c210cC5leG1haWwucXEuY29t
  user: d2ViYm90QHpkbnMuY24=
kind: Secret
metadata:
  name: zddiweb-email
  namespace: cicd
type: Opaque
