apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-listener-interceptor
  namespace: cicd
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: push-pipeline
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
      bindings:
        - name: gitlab-event-bindings
      template:
        name: zddiv3-web-push-pipeline
