apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: lint-ui-run-
  namespace: cicd
spec:
  serviceAccountName: pipeline-run-service
  taskRef:
    name: node-lint
  inputs:
    params:
      - name: prefix
        value: packages/ui
    resources:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/zdnscloud/singlecloud-ui
