apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: singlecloud-ui-image
spec:
  type: image
  params:
    - name: url
      value: registry.zdns.cn/zcloud/singlecloud-ui 

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: singlecloud-image
spec:
  type: image
  params:
    - name: url
      value: registry.zdns.cn/zcloud/singlecloud

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: zcloud-image
spec:
  type: image
  params:
    - name: url
      value: registry.zdns.cn/zcloud/zcloud

