apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: build-image-from-git-run-
spec:
  serviceAccountName: pipeline-run-service
  taskRef:
    name: build-image-from-git
  inputs:
    resources:
      - name: docker-source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/zdnscloud/singlecloud
    params:
      - name: imageTagName
        value: slave
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: singlecloud-image
