apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: zddiv3-web-lint
  namespace: cicd
spec:
  params:
  - name: revision
    description: The git revision
    default: master
  - name: repository_url
    description: The git repository url
    default: git@git.zdns.cn:zdns/zddiv3-web.git
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: npm-run-lint-
        namespace: cicd
      spec:
          serviceAccountName: pipeline-run-service
          taskRef:
            name: npm-run
          params:
            - name: cmd
              value: lint
          resources:
            inputs:
              - name: source
                resourceSpec:
                  type: git
                  params:
                    - name: revision
                      value: $(params.revision)
                    - name: url
                      value: $(params.repository_url)
                    - name: submodules
                      value: "false"

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: zddiv3-web-test
  namespace: cicd
spec:
  params:
  - name: revision
    description: The git revision
    default: master
  - name: repository_url
    description: The git repository url
    default: git@git.zdns.cn:zdns/zddiv3-web.git
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: npm-run-lint-
        namespace: cicd
      spec:
          serviceAccountName: pipeline-run-service
          taskRef:
            name: npm-run
          params:
            - name: cmd
              value: test
          resources:
            inputs:
              - name: source
                resourceSpec:
                  type: git
                  params:
                    - name: revision
                      value: $(params.revision)
                    - name: url
                      value: $(params.repository_url)
                    - name: submodules
                      value: "false"


